STARTUP;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER dbuser IDENTIFIED BY welcome ACCOUNT UNLOCK;
GRANT CREATE SESSION TO dbuser;
GRANT CREATE TABLE TO dbuser;
ALTER USER dbuser QUOTA UNLIMITED ON USERS;
SET WRAP ON;
SET LINES 150;
EXIT;
