STARTUP;

CREATE PLUGGABLE DATABASE mydb ADMIN USER user1 IDENTIFIED BY welcome FILE_NAME_CONVERT=('/opt/oracle/oradata/XE/pdbseed','/opt/oracle/oradata/XE/mydb');

ALTER PLUGGABLE DATABASE mydb OPEN;

ALTER SESSION SET CONTAINER="MYDB";

CREATE USER user1 IDENTIFIED BY welcome ACCOUNT UNLOCK;
GRANT CREATE SESSION TO user1;

EXIT;
